# manifests/demo-app-vai.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
      annotations:
        # enable the vault agent injector
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/error-on-missing-key : "true"
        # secrets path
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/postgres"
        # template
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/postgres" -}}
          export DB_USER="{{ .Data.username }}"
          export DB_PASSWORD="{{ .Data.password }}"
          {{- end }}
        vault.hashicorp.com/role: "vai"
        vault.hashicorp.com/tls-skip-verify: "true"
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: vault-from-zero-to-hero
          image: falcosuessgott/vault-from-zero-to-hero
          command:
            - sh
            - -c
          args:
            # source the env vars before starting the app
            - source /vault/secrets/db-creds && /demo-app
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              value: "172.17.0.1"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: vault
