# manifests/demo-app-hardcoded.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: vault-from-zero-to-hero
          image: falcosuessgott/vault-from-zero-to-hero
          ports:
            - containerPort: 9090
          env:
            # This is bad - do not do this!
            - name: DB_HOST
              value: host.docker.internal
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: P@ssw0rd
            - name: DB_NAME
              value: vault
