apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://172.17.0.1:8200
      path: secret
      version: v2
      auth:
        appRole:
          roleId: 3b836ce4-7769-0f54-2d1f-ccba336f66f3
          secretRef:
            name: vault-approle
            key: secret-id
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-approle
data:
  secret-id: NjlkZjNkZjItNWZjOS05MDQxLTcxNTEtMmVlMThhMDJhNWEw
