apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-creds
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-creds
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: database/postgres
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: database/postgres
        property: DB_PORT
    - secretKey: DB_USER
      remoteRef:
        key: database/postgres
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: database/postgres
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: database/postgres
        property: DB_NAME
