# manifests/kind-config.yml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          certSANs:
            - host.docker.internal
            - localhost
            - 127.0.0.1
            - 172.17.0.1
            - 0.0.0.0
  - role: worker
  - role: worker
